# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lozQJBrC_D2z5iFvsL4B9DcNveJwcTB9

#Unit converter
"""

import streamlit as st

st.title("Unit Converter")

conversion_type = st.selectbox(
    "Choose Conversion Type",
    ("Length (meters to kilometers)", "Weight (grams to kilograms)", "Temperature (Celsius to Fahrenheit)")
)

number = st.number_input("Enter the value you want to convert:")

if conversion_type == "Length (meters to kilometers)":
    result = number / 1000
    st.write(f"{number} meters is {result} kilometers.")

elif conversion_type == "Weight (grams to kilograms)":
    result = number / 1000
    st.write(f"{number} grams is {result} kilograms.")

elif conversion_type == "Temperature (Celsius to Fahrenheit)":
    result = (number * 9/5) + 32
    st.write(f"{number} °C is {result} °F.")
